apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    app: postgres
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql